### ISSUE TITLE
Refactoring unit test for deep-db module

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/deep-framework#48]
Refactoring unit tests for deep-db module to have the same approach to create Kernel instance from config file.
Loading all services by Kernel.get(). Update/create mocks to have the same approach for all modules.

**Comment by vcernomschi** [comment]
Moved to next release, because was not able to finished in time due to spending more time to refactor deep-resource (complex methods, many mocks), deep-fs (was added new unit tests to cover new functionality added by AlexanderC), deep-log (many mocks, resolving issues to dynamically inject mocks with proxyquire)
