### ISSUE TITLE
Refactoring unit test for deep-security module

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/deep-framework#52]
Refactoring unit tests for deep-security module to have the same approach to create Kernel instance from config file.
Loading all services by Kernel.get(). Update/create mocks to have the same approach for all modules.

**Comment by vcernomschi** [comment]
Marcel is updating this module

**Comment by vcernomschi** [comment]
Moved to next release (is in updating by Marcel G), and was not able to finished in time due to spending more time than had planned to refactor deep-resource (complex methods, many mocks), deep-fs (was added new unit tests to cover new functionality added by AlexanderC), deep-log (many mocks, resolving issues to dynamically inject mocks with proxyquire)

**Comment by vcernomschi** [comment]
Unit testing is in implementing  stage now. Moved to next release.
