### ISSUE TITLE
[deep-security] Refactor user provider to load user directly from DB

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-framework#570]
Refactor user provider to load user directly from DB instead of a separate call through API Gateway

**Comment by mgoria** [comment]
Steps to test:

1. Find a lambda that uses `.getUser()`  method to load logged user
2. Deploy this app with x-ray enabled
3. Invoke the lambda in the subject
4. Inspect lambda trace in x-ray (there should be calls to retrieve user lambda, user should be loaded directly from DynamoDB)

**Comment by avozicov** [comment]
**Test Passed**
- Lambda trace in X-Ray service should contain information that user was loaded from Dynamo DB instead of API Gateway service
<img width="1255" alt="screen shot 2017-06-22 at 2 10 59 pm" src="https://user-images.githubusercontent.com/12330493/27431433-3263d59a-5755-11e7-94f1-38c62c23b8f1.png">
